<br>
<br>
<h1 align="center">Heart Disease</h1>
<br>
<br>

## $\triangleright$ Our dataset :
<a href="https://www.kaggle.com/ronitf/heart-disease-uci/version/1#heart.csv">Kaggle - Heart Disease UCI</a>
<br>
<br>
$\bullet$ This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them. In particular, the Cleveland database is the only one that has been used by ML researchers to this date. The "goal" field refers to the presence of heart disease in the patient. It is integer valued from 0 (no presence) to 4.

Attribute Information: 
1. age 
2. sex 
3. chest pain type (4 values) 
4. resting blood pressure 
5. serum cholestoral in mg/dl 
6. fasting blood sugar > 120 mg/dl
7. resting electrocardiographic results (values 0,1,2)
8. maximum heart rate achieved 
9. exercise induced angina 
10. oldpeak = ST depression induced by exercise relative to rest 
11. the slope of the peak exercise ST segment 
12. number of major vessels (0-3) colored by flourosopy 
13. thal: 3 = normal; 6 = fixed defect; 7 = reversable defect

14. target

## $\triangleright$ Libraries we use :

In [385]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from sklearn.model_selection import train_test_split

## $\triangleright$ Read the dataset :


In [386]:
dataset = pd.read_csv('heart.csv')
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [387]:
dataset.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0

## $\triangleright$ Separation and Normalization:

In [388]:
#Separate the data to features,target
columns=['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
features = np.array(pd.read_csv('heart.csv',usecols=columns))

target = np.array(pd.read_csv('heart.csv',usecols=["target"]))

#Normalization
scaler = MinMaxScaler(feature_range=(0, 1))
features = scaler.fit_transform(features)
print(features)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


## $\triangleright$ Create the feature columns to be accessed in the model

In [389]:
#Create the feature columns
feature_columns = [tf.feature_column.numeric_column(k) for k in columns]

print(feature_columns)

[_NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='sex', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='cp', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='trestbps', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='chol', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='fbs', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='restecg', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='thalach', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='exang', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericColumn(key='oldpeak', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), _NumericCo

## $\triangleright$ Train-Test split

In [390]:
trainX,testX,trainY,testY = train_test_split(features,target,test_size=0.3)

#Turn to array
trainX = np.array(trainX)
testX = np.array(testX)
trainY = np.array(trainY)
testY = np.array(testY)

trainX={'age':trainX[:,0],'sex':trainX[:,1],'cp':trainX[:,2],'trestbps':trainX[:,3],'chol':trainX[:,4],'fbs':trainX[:,5],'restecg':trainX[:,6],'thalach':trainX[:,7],'exang':trainX[:,8],'oldpeak':trainX[:,9],'slope':trainX[:,10],'ca':trainX[:,11],'thal':trainX[:,12]}
testX={'age':testX[:,0],'sex':testX[:,1],'cp':testX[:,2],'trestbps':testX[:,3],'chol':testX[:,4],'fbs':testX[:,5],'restecg':testX[:,6],'thalach':testX[:,7],'exang':testX[:,8],'oldpeak':testX[:,9],'slope':testX[:,10],'ca':testX[:,11],'thal':testX[:,12]}

## $\triangleright$ Input function

In [391]:
classifier = tf.estimator.DNNClassifier(
 feature_columns=feature_columns,
 hidden_units=[256, 32],
 optimizer=tf.train.AdamOptimizer(1e-4),
 n_classes=len(columns),
)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpgtltqt2n', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fccfee57cf8>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


## $\triangleright$ Creating the model

In [392]:
train_input_fn = tf.estimator.inputs.numpy_input_fn(
 x=trainX,
 y=trainY,
 num_epochs=None,
 batch_size=1,
 shuffle=True
)
classifier.train(input_fn=train_input_fn, steps=10000)

test_input_fn = tf.estimator.inputs.numpy_input_fn(
    x=testX,
    y=testY,
    num_epochs=1,
    shuffle=False
)

accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]
print("\nTest Accuracy: {0:f}%\n".format(accuracy_score*100))

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpgtltqt2n/model.ckpt.
INFO:tensorflow:loss = 2.6184893, step = 1
INFO:tensorflow:global_step/sec: 472.134
INFO:tensorflow:loss = 2.3050663, step = 101 (0.216 sec)
INFO:tensorflow:global_step/sec: 672.228
INFO:tensorflow:loss = 2.002651, step = 201 (0.146 sec)
INFO:tensorflow:global_step/sec: 626.896
INFO:tensorflow:loss = 0.9489124, step = 301 (0.165 sec)
INFO:tensorflow:global_step/sec: 653.541
INFO:tensorflow:loss = 1.2532661, step = 401 (0.153 sec)
INFO:tensorflow:global_step/sec: 694.994
INFO:tensorflow:loss = 0.5185982, step = 501 (0.140 sec)
INFO:tensorflow:global_step/sec: 768.925
INFO:tensorflow:loss = 0.7270229, step = 601 (0.132 sec)
INFO:tensorflow:global_step/sec: 598.567
INFO:tensorflow:loss = 0.38063926, step = 701 (0.163 sec)
INFO:tensorflow:global_step/sec: 667.617
INFO:tensorflow:loss = 1.123502, step = 801 (0.153 sec)
INFO:tensorflow:global_step/sec: 633.594
INFO:tensorflo

INFO:tensorflow:global_step/sec: 738.725
INFO:tensorflow:loss = 0.15165098, step = 8201 (0.135 sec)
INFO:tensorflow:global_step/sec: 690.485
INFO:tensorflow:loss = 0.112372324, step = 8301 (0.145 sec)
INFO:tensorflow:global_step/sec: 651.728
INFO:tensorflow:loss = 0.9627322, step = 8401 (0.153 sec)
INFO:tensorflow:global_step/sec: 583.013
INFO:tensorflow:loss = 0.051250182, step = 8501 (0.177 sec)
INFO:tensorflow:global_step/sec: 616.16
INFO:tensorflow:loss = 0.007048148, step = 8601 (0.158 sec)
INFO:tensorflow:global_step/sec: 580.503
INFO:tensorflow:loss = 0.44251466, step = 8701 (0.176 sec)
INFO:tensorflow:global_step/sec: 561.174
INFO:tensorflow:loss = 0.03950846, step = 8801 (0.174 sec)
INFO:tensorflow:global_step/sec: 600.536
INFO:tensorflow:loss = 0.39324114, step = 8901 (0.165 sec)
INFO:tensorflow:global_step/sec: 630.441
INFO:tensorflow:loss = 0.012185651, step = 9001 (0.160 sec)
INFO:tensorflow:global_step/sec: 718.548
INFO:tensorflow:loss = 0.2854429, step = 9101 (0.138 sec)

In [393]:
linearClassifier =tf.estimator.LinearClassifier(feature_columns=feature_columns,n_classes=len(columns))
linearClassifier.train(input_fn=train_input_fn,steps=10000)
accuracy_score = linearClassifier.evaluate(input_fn=test_input_fn)["accuracy"]
print("\nTest Accuracy: {0:f}%\n".format(accuracy_score*100))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpwnwbsyt6', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fcd0ac59860>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpwnwbsyt6/model.ckpt.
INFO:tensorflow:loss = 2.5649493, step = 1
INFO:tensorflow:global_step/sec: 527.256
INFO:tensorflow:loss = 1.3851583, step = 101 (0.195 sec)
INFO:tensorflow:global_step/sec: 646.886
INFO:tensorflow:loss = 0.22168031, step = 201 (0.153 sec)
INFO:tensorflow:global_step/sec: 650.303
INFO:tensorflow:loss 

INFO:tensorflow:loss = 1.8742077, step = 7501 (0.129 sec)
INFO:tensorflow:global_step/sec: 717.9
INFO:tensorflow:loss = 1.1963419, step = 7601 (0.139 sec)
INFO:tensorflow:global_step/sec: 753.802
INFO:tensorflow:loss = 0.071400434, step = 7701 (0.133 sec)
INFO:tensorflow:global_step/sec: 672.251
INFO:tensorflow:loss = 0.17936362, step = 7801 (0.149 sec)
INFO:tensorflow:global_step/sec: 697.574
INFO:tensorflow:loss = 0.23118693, step = 7901 (0.149 sec)
INFO:tensorflow:global_step/sec: 588.198
INFO:tensorflow:loss = 0.25153765, step = 8001 (0.165 sec)
INFO:tensorflow:global_step/sec: 680.377
INFO:tensorflow:loss = 1.0025344, step = 8101 (0.147 sec)
INFO:tensorflow:global_step/sec: 687.025
INFO:tensorflow:loss = 0.42807245, step = 8201 (0.146 sec)
INFO:tensorflow:global_step/sec: 717.267
INFO:tensorflow:loss = 0.044434387, step = 8301 (0.140 sec)
INFO:tensorflow:global_step/sec: 640.628
INFO:tensorflow:loss = 0.34802556, step = 8401 (0.156 sec)
INFO:tensorflow:global_step/sec: 692.292
INF

In [394]:
classifier.evaluate(test_input_fn)

INFO:tensorflow:Starting evaluation at 2019-03-25-01:49:40
INFO:tensorflow:Restoring parameters from /tmp/tmpgtltqt2n/model.ckpt-10000
INFO:tensorflow:Finished evaluation at 2019-03-25-01:49:41
INFO:tensorflow:Saving dict for global step 10000: accuracy = 0.84615386, average_loss = 0.43457106, global_step = 10000, loss = 39.545967


{'accuracy': 0.84615386,
 'average_loss': 0.43457106,
 'loss': 39.545967,
 'global_step': 10000}